# Generated by Django 2.1.5 on 2019-01-09 09:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='username',
            field=models.CharField(default='', max_length=255, unique=True, validators=[django.core.validators.RegexValidator(regex='^[\\w\\.@-]*$')]),
        ),
    ]
